// Demo content for "Beispiel anhören" and for the recognition stub (src/scan/recognize.ts).
//
// J. S. Bach's four-part harmonisation of "Nun danket alle Gott" (melody: Johann Crüger, 1647), BWV 386 –
// published in "371 vierstimmige Choralgesänge", 4th ed., ed. Alfred Dörffel (Breitkopf & Härtel, c. 1875),
// long in the public domain. Pickup plus the first four bars (the opening phrase up to its fermata cadence).
// Pitches, rhythm, key (A major, MM 100) cross-checked against the Humdrum **kern transcription
// kern/chor032.krn in https://github.com/craigsapp/bach-370-chorales (Bass/Tenor/Alto/Soprano column order).
import type { Score } from './score';

export const demoScore: Score = {
  beatsPerBar: 4,
  keyFifths: 3, // A major: F#, C#, G#
  tempo: 100,
  voices: {
    S: [
      { midi: 76, start: 0, duration: 1, bar: 0 },
      { midi: 76, start: 1, duration: 1, bar: 1 },
      { midi: 76, start: 2, duration: 1, bar: 1 },
      { midi: 78, start: 3, duration: 1, bar: 1 },
      { midi: 78, start: 4, duration: 1, bar: 1 },
      { midi: 76, start: 5, duration: 2, bar: 2 },
      { midi: null, start: 7, duration: 1, bar: 2 },
      { midi: 73, start: 8, duration: 1, bar: 2 },
      { midi: 74, start: 9, duration: 1, bar: 3 },
      { midi: 73, start: 10, duration: 1, bar: 3 },
      { midi: 71, start: 11, duration: 1, bar: 3 },
      { midi: 73, start: 12, duration: 0.5, bar: 3 },
      { midi: 74, start: 12.5, duration: 0.5, bar: 3 },
      { midi: 71, start: 13, duration: 2, bar: 4 },
      { midi: 69, start: 15, duration: 1, bar: 4 },
    ],
    A: [
      { midi: 69, start: 0, duration: 1, bar: 0 },
      { midi: 69, start: 1, duration: 1, bar: 1 },
      { midi: 69, start: 2, duration: 1, bar: 1 },
      { midi: 69, start: 3, duration: 1, bar: 1 },
      { midi: 69, start: 4, duration: 1, bar: 1 },
      { midi: 69, start: 5, duration: 2, bar: 2 },
      { midi: null, start: 7, duration: 1, bar: 2 },
      { midi: 69, start: 8, duration: 1, bar: 2 },
      { midi: 71, start: 9, duration: 1, bar: 3 },
      { midi: 69, start: 10, duration: 1, bar: 3 },
      { midi: 68, start: 11, duration: 1, bar: 3 },
      { midi: 69, start: 12, duration: 1, bar: 3 },
      { midi: 69, start: 13, duration: 0.5, bar: 4 },
      { midi: 66, start: 13.5, duration: 0.5, bar: 4 },
      { midi: 68, start: 14, duration: 1, bar: 4 },
      { midi: 64, start: 15, duration: 1, bar: 4 },
    ],
    T: [
      { midi: 61, start: 0, duration: 1, bar: 0 },
      { midi: 61, start: 1, duration: 1, bar: 1 },
      { midi: 61, start: 2, duration: 1, bar: 1 },
      { midi: 62, start: 3, duration: 1, bar: 1 },
      { midi: 62, start: 4, duration: 1, bar: 1 },
      { midi: 61, start: 5, duration: 2, bar: 2 },
      { midi: null, start: 7, duration: 1, bar: 2 },
      { midi: 66, start: 8, duration: 1, bar: 2 },
      { midi: 64, start: 9, duration: 1, bar: 3 },
      { midi: 64, start: 10, duration: 1, bar: 3 },
      { midi: 64, start: 11, duration: 1, bar: 3 },
      { midi: 64, start: 12, duration: 1, bar: 3 },
      { midi: 64, start: 13, duration: 0.5, bar: 4 },
      { midi: 62, start: 13.5, duration: 0.25, bar: 4 },
      { midi: 61, start: 13.75, duration: 0.25, bar: 4 },
      { midi: 62, start: 14, duration: 1, bar: 4 },
      { midi: 61, start: 15, duration: 1, bar: 4 },
    ],
    B: [
      { midi: 45, start: 0, duration: 1, bar: 0 },
      { midi: 57, start: 1, duration: 0.5, bar: 1 },
      { midi: 59, start: 1.5, duration: 0.5, bar: 1 },
      { midi: 61, start: 2, duration: 0.5, bar: 1 },
      { midi: 57, start: 2.5, duration: 0.5, bar: 1 },
      { midi: 50, start: 3, duration: 0.5, bar: 1 },
      { midi: 52, start: 3.5, duration: 0.5, bar: 1 },
      { midi: 54, start: 4, duration: 0.5, bar: 1 },
      { midi: 50, start: 4.5, duration: 0.5, bar: 1 },
      { midi: 57, start: 5, duration: 2, bar: 2 },
      { midi: null, start: 7, duration: 1, bar: 2 },
      { midi: 57, start: 8, duration: 1, bar: 2 },
      { midi: 56, start: 9, duration: 1, bar: 3 },
      { midi: 57, start: 10, duration: 1, bar: 3 },
      { midi: 52, start: 11, duration: 0.5, bar: 3 },
      { midi: 50, start: 11.5, duration: 0.5, bar: 3 },
      { midi: 49, start: 12, duration: 0.5, bar: 3 },
      { midi: 45, start: 12.5, duration: 0.5, bar: 3 },
      { midi: 52, start: 13, duration: 2, bar: 4 },
      { midi: 45, start: 15, duration: 1, bar: 4 },
    ],
  },
};
